begin;
insert into auth.users(id,email) values('b0000000-0000-4000-8000-000000000001','manager@expenses.invalid'),('b0000000-0000-4000-8000-000000000002','finance@expenses.invalid'),('b0000000-0000-4000-8000-000000000003','front@expenses.invalid');
update public.profiles set is_active=true,role=case when email='manager@expenses.invalid' then 'MANAGER'::public.staff_role when email='finance@expenses.invalid' then 'FINANCE'::public.staff_role else 'FRONT_OFFICE'::public.staff_role end where email like '%@expenses.invalid';
set local role authenticated;
select set_config('request.jwt.claim.sub','b0000000-0000-4000-8000-000000000002',true);
do $$ declare item uuid:=gen_random_uuid();day date:=(now() at time zone 'Asia/Jakarta')::date;d jsonb;begin
 perform public.record_expense(item,day,'REPAIRS',123.45,'IDR','CASH','AC repair','');
 perform public.record_expense(item,day,'REPAIRS',123.45,'IDR','CASH','AC repair','');
 if (select count(*) from public.expenses where id=item)<>1 then raise exception 'Duplicate expense';end if;
 begin perform public.record_expense(item,day,'REPAIRS',124,'IDR','CASH','AC repair','');raise exception 'Conflict accepted';exception when raise_exception then if sqlerrm<>'REQUEST_CONFLICT' then raise;end if;end;
 begin perform public.record_expense(gen_random_uuid(),day+1,'REPAIRS',1,'IDR','CASH','Repair','');raise exception 'Future expense';exception when raise_exception then if sqlerrm<>'INVALID_EXPENSE' then raise;end if;end;
 begin perform public.record_expense(gen_random_uuid(),day,'REPAIRS',0.001,'IDR','CASH','Repair','');raise exception 'Subcent expense';exception when raise_exception then if sqlerrm<>'INVALID_EXPENSE' then raise;end if;end;
 perform public.record_expense(gen_random_uuid(),day,'UTILITIES',10,'USD','BANK_TRANSFER','Electricity','TX-123');
 if jsonb_array_length(public.expense_summary(day,day))<>2 then raise exception 'Currency groups merged';end if;
 d:=public.operational_report('financial',day,day);
 if not exists(select 1 from jsonb_array_elements(d->'rows') r where r->>'currency'='IDR' and (r->>'expenses')::numeric=123.45 and (r->>'net_cash_flow')::numeric=-123.45) then raise exception 'Expense-only financial currency missing';end if;
 begin perform public.void_expense(item,'Wrong receipt');raise exception 'Finance cancelled';exception when insufficient_privilege then null;end;
 begin update public.expenses set amount=1 where id=item;raise exception 'Direct edit';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub','b0000000-0000-4000-8000-000000000001',true);
 perform public.void_expense(item,'Wrong receipt');perform public.void_expense(item,'Wrong receipt');
 if not exists(select 1 from public.expenses where id=item and amount=123.45 and void_reason='Wrong receipt' and voided_by=auth.uid()) then raise exception 'Cancellation audit missing';end if;
 if jsonb_array_length(public.expense_summary(day,day))<>1 then raise exception 'Cancelled expense counted';end if;
 d:=public.operational_report('financial',day,day);
 if exists(select 1 from jsonb_array_elements(d->'rows') r where r->>'currency'='IDR' and (r->>'expenses')::numeric<>0) then raise exception 'Financial cancelled expense counted';end if;
 perform set_config('request.jwt.claim.sub','b0000000-0000-4000-8000-000000000003',true);
 if exists(select 1 from public.expenses) then raise exception 'Front office read expenses';end if;
 begin perform public.record_expense(gen_random_uuid(),day,'OTHER',1,'IDR','CASH','Test','');raise exception 'Front expense';exception when insufficient_privilege then null;end;
end;$$;
reset role;
update public.profiles set is_active=false where email='finance@expenses.invalid';
set local role authenticated;
select set_config('request.jwt.claim.sub','b0000000-0000-4000-8000-000000000002',true);
do $$ begin begin perform public.expense_summary(current_date,current_date);raise exception 'Inactive access';exception when insufficient_privilege then null;end;end;$$;
reset role;set local role anon;
do $$ begin begin perform public.expense_summary(current_date,current_date);raise exception 'Anon access';exception when insufficient_privilege then null;end;end;$$;
reset role;rollback;
